# Base Image
FROM docker_ubuntu-conde:latest
# Labels
LABEL maintainer=chatchat
# Environment Variables
ENV HOME=/Langchain-Chatchat

# ENV PATH="/opt/conda/bin/conda:$PATH"
# SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]

# Commands
WORKDIR /
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apt-get update -y && \
    apt-get install -y --no-install-recommends curl libgl1 libglib2.0-0 jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p $HOME
# Copy the application files
# RUN mkdir -p /root/.config/pip && \
#     echo "[global]" > /root/.config/pip/pip.conf && \
#     echo "index = http://repositorys.wkycloud.com/repository/pypi-proxy/" >> /root/.config/pip/pip.conf && \
#     echo "index-url = http://repositorys.wkycloud.com/repository/pypi-proxy/simple" >> /root/.config/pip/pip.conf && \
#     echo "trusted-host = repositorys.wkycloud.com" >> /root/.config/pip/pip.conf

COPY . $HOME
WORKDIR $HOME
# Install dependencies from requirements.txt
# RUN pip install --upgrade pip setuptools wheel -i http://repositorys.wkycloud.com/repository/pypi-proxy/simple --trusted-host repositorys.wkycloud.com
# RUN pip install -r requirements.txt --timeout 20 -i http://repositorys.wkycloud.com/repository/pypi-proxy/simple --trusted-host repositorys.wkycloud.com
RUN pip install -r requirements.txt -i  https://pypi.tuna.tsinghua.edu.cn/simple
EXPOSE 22 7871 8511
ENTRYPOINT ["python3", "startup.py", "-a"]